//PKP

GET http://localhost:5000/pkp

###
GET http://localhost:5000/pkp/1

###
POST http://localhost:5000/pkp
Content-Type: application/json

{
    "npd_pkp": "UPPPD Tebet",
    "kpd_pkp": "3015",
    "nipd_pkp": "UPPPD Tebet",
    "tr_pkp": "2023-01-15",
    "tm_pkp": "2023-01-15",
    "alamat_pkp": "Kantor Kecamatan Tebet Lt. 3, Jl. Prof. DR. Soepomo No.55C, Tebet, Jakarta Selatan",
    "kota_pkp": "Jakarta Selatan",
    "kp_pkp": "12810",
    "nki_pkp": "Kepala Instansi UPPPD Tebet",
    "tlp_pkp": "02147884158",
    "email_pkp": "upppd.tebet@jakarta.go.id",
    "lpd_pkp": "Foto",
    "fkipd_pkp": "Foto"
}

###
PATCH http://localhost:5000/pkp/1
Content-Type: application/json

{
    "npd_pkp": "UPPPD Pulo Gadung",
    "kpd_pkp": "3175",
    "nipd_pkp": "UPPPD Pulo Gadung",
    "tr_pkp": "2023-01-14",
    "tm_pkp": "2023-01-14",
    "alamat_pkp": "Kantor Kecamatan Pulo Gadung, Jl. Raya Bekasi KM. 18, Pulo Gadung, Jakarta Timur",
    "kota_pkp": "Jakarta Timur",
    "kp_pkp": "13250",
    "nki_pkp": "Kepala Instansi UPPPD Pulo Gadung",
    "tlp_pkp": "02147884158",
    "email_pkp": "upppd.pulogadung@jakarta.go.id",
    "lpd_pkp": "Foto",
    "fkipd_pkp": "Foto"
}

###
DELETE http://localhost:5000/pkp/5

//PWP

###
GET http://localhost:5000/pwp

###
GET http://localhost:5000/pwp/2

###
POST http://localhost:5000/pwp
Content-Type: application/json

{
    "np_pwp": "17345",
    "nwp_pwp": "Yopita Sari",
    "alamat_pwp": "JL.Contoh NO.56, Kecamatan Pulo Gadung, Pulo Gadung, Jakarta Timur",
    "kel_pwp": "Pulo Gebang",
    "kec_pwp": "Pulo Gadung",
    "kp_pwp": "13250",
    "npwdp_pwp": "123123123742",
    "email_pwp": "yopita.sari@gmail.com",
    "tr_pwp": "2023-01-17",
    "tm_pwp": "2023-01-17",
    "jumlah_outlet_pwp": "1",
    "jenis_outlet_pwp": "Ruko",
    "jenis_pajak_pwp": "Bangunan",
    "logo_pwp": "Foto",
    "ftdp_pwp": "Foto",
    "si_pwp": "Foto"
}

###
PATCH http://localhost:5000/pwp/1
Content-Type: application/json

{
    "np_pwp": "17345",
    "nwp_pwp": "Yopita Sari",
    "alamat_pwp": "JL.Contoh NO.56, Kecamatan Pulo Gadung, Pulo Gadung, Jakarta Timur",
    "kel_pwp": "Pulo Gebang",
    "kec_pwp": "Pulo Gadung",
    "kp_pwp": "13250",
    "npwdp_pwp": "123123123742",
    "email_pwp": "yopita.sari@gmail.com",
    "tr_pwp": "2023-01-17",
    "tm_pwp": "2023-01-17",
    "jumlah_outlet_pwp": "1",
    "jenis_outlet_pwp": "Ruko",
    "jenis_pajak_pwp": "Bangunan",
    "logo_pwp": "Foto",
    "ftdp_pwp": "Foto",
    "si_pwp": "Foto"
}

###
DELETE http://localhost:5000/pwp/1

//PPL

###
GET http://localhost:5000/ppl

###
GET http://localhost:5000/ppl/2

###
POST http://localhost:5000/ppl
Content-Type: application/json

{
    "nip_ppl": "17",
    "np_ppl": "Nicki",
    "alamat_ppl": "Kantor Kecamatan Senen, Jl. Kramat Raya No. 114, Senen, Jakarta Pusat 10450",
    "kel_ppl": "Senen",
    "kec_ppl": "Jakarta Pusat",
    "kp_ppl": "10450",
    "nik_ppl": "263982736482938172",
    "tr_ppl": "2023-01-17",
    "tm_ppl": "2023-01-17",
    "tlp_ppl": "081182736742",
    "email_ppl": "nicki@gmail.com",
    "foto_ktp_ppl": "Foto",
    "pas_foto_ppl": "Foto"
}

###
PATCH http://localhost:5000/ppl/1
Content-Type: application/json

{
    "nip_ppl": "17",
    "np_ppl": "Nicki",
    "alamat_ppl": "Kantor Kecamatan Senen, Jl. Kramat Raya No. 114, Senen, Jakarta Pusat 10450",
    "kel_ppl": "Senen",
    "kec_ppl": "Jakarta Pusat",
    "kp_ppl": "10450",
    "nik_ppl": "263982736482938172",
    "tr_ppl": "2023-01-17",
    "tm_ppl": "2023-01-17",
    "tlp_ppl": "081182736742",
    "email_ppl": "nicki@gmail.com",
    "foto_ktp_ppl": "Foto",
    "pas_foto_ppl": "Foto"
}

###
DELETE http://localhost:5000/ppl/1

//PAFE

###
GET http://localhost:5000/pafe

###
GET http://localhost:5000/pafe/1

###
POST http://localhost:5000/pafe
Content-Type: application/json

{
    "nwp_pafe": "Joserizar",
    "no_pafe": "Outlet TGN",
    "oi_pafe": "17",
    "ja_pafe": "Tapping Box",
    "afe_pafe": "Ts-108",
    "ip_pafe": "192.168.38.1.",
    "ai_pafe": "171",
    "tr_pafe": "2023-01-24",
    "tm_pafe": "2023-01-24",
    "longitude_pafe": "106.87780701072914",
    "latitude_pafe": "-6.171625895730746",
    "fpa_pafe": "Foto",
    "fsna_pafe": "Foto",
    "sn_pafe": "Foto"
}

###
PATCH http://localhost:5000/pafe/1
Content-Type: application/json

{
    "nwp_pafe": "Joserizar",
    "no_pafe": "TGN",
    "oi_pafe": "17",
    "ja_pafe": "Tapping Box",
    "afe_pafe": "Ts-108",
    "ip_pafe": "192.168.38.1.",
    "ai_pafe": "171",
    "tr_pafe": "2023-01-24",
    "tm_pafe": "2023-01-24",
    "longitude_pafe": "106.87780701072914",
    "latitude_pafe": "-6.171625895730746",
    "fpa_pafe": "Foto",
    "fsna_pafe": "Foto",
    "sn_pafe": "Foto"
}

###
DELETE http://localhost:5000/pafe/1